In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [5]:
#read data
churnData = pd.read_excel('Data/Telco_customer_churn.xlsx')
demoData = pd.read_excel('Data/Telco_customer_churn_demographics.xlsx')
locData = pd.read_excel('Data/Telco_customer_churn_location.xlsx')
popData = pd.read_excel('Data/Telco_customer_churn_population.xlsx')
servData = pd.read_excel('Data/Telco_customer_churn_services.xlsx')
statusData = pd.read_excel('Data/Telco_customer_churn_status.xlsx')

In [35]:
popData.head()

   ID  Zip Code  Population
0   1     90001       54492
1   2     90002       44586
2   3     90003       58198
3   4     90004       67852
4   5     90005       43019

In [46]:
rawData = churnData.merge(demoData,on='CustomerID').merge(locData,on='CustomerID').merge(servData,on='CustomerID').merge(statusData,on='CustomerID')

In [47]:
rawData.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7043 entries, 0 to 7042
Data columns (total 88 columns):
CustomerID                           7043 non-null object
Count_x                              7043 non-null int64
Country_x                            7043 non-null object
State_x                              7043 non-null object
City_x                               7043 non-null object
Zip Code_x                           7043 non-null int64
Lat Long_x                           7043 non-null object
Latitude_x                           7043 non-null float64
Longitude_x                          7043 non-null float64
Gender_x                             7043 non-null object
Senior Citizen_x                     7043 non-null object
Partner                              7043 non-null object
Dependents_x                         7043 non-null object
Tenure Months                        7043 non-null int64
Phone Service_x                      7043 non-null object
Multiple Lines_x                     7043 non-null object
Internet Service_x                   7043 non-null object
Online Security_x                    7043 non-null object
Online Backup_x                      7043 non-null object
Device Protection                    7043 non-null object
Tech Support                         7043 non-null object
Streaming TV_x                       7043 non-null object
Streaming Movies_x                   7043 non-null object
Contract_x                           7043 non-null object
Paperless Billing_x                  7043 non-null object
Payment Method_x                     7043 non-null object
Monthly Charges                      7043 non-null float64
Total Charges_x                      7043 non-null object
Churn Label_x                        7043 non-null object
Churn Value_x                        7043 non-null int64
Churn Score_x                        7043 non-null int64
CLTV_x                               7043 non-null int64
Churn Reason_x                       1869 non-null object
Count_y                              7043 non-null int64
Gender_y                             7043 non-null object
Age                                  7043 non-null int64
Under 30                             7043 non-null object
Senior Citizen_y                     7043 non-null object
Married                              7043 non-null object
Dependents_y                         7043 non-null object
Number of Dependents                 7043 non-null int64
Count_x                              7043 non-null int64
Country_y                            7043 non-null object
State_y                              7043 non-null object
City_y                               7043 non-null object
Zip Code_y                           7043 non-null int64
Lat Long_y                           7043 non-null object
Latitude_y                           7043 non-null float64
Longitude_y                          7043 non-null float64
Count_y                              7043 non-null int64
Quarter_x                            7043 non-null object
Referred a Friend                    7043 non-null object
Number of Referrals                  7043 non-null int64
Tenure in Months                     7043 non-null int64
Offer                                7043 non-null object
Phone Service_y                      7043 non-null object
Avg Monthly Long Distance Charges    7043 non-null float64
Multiple Lines_y                     7043 non-null object
Internet Service_y                   7043 non-null object
Internet Type                        7043 non-null object
Avg Monthly GB Download              7043 non-null int64
Online Security_y                    7043 non-null object
Online Backup_y                      7043 non-null object
Device Protection Plan               7043 non-null object
Premium Tech Support                 7043 non-null object
Streaming TV_y                       7043 non-null object
Streaming Movies_y                   7043 non-null object
Streaming Music                      7043 non-null object
Unlimited Data                       7043 non-null object
Contract_y                           7043 non-null object
Paperless Billing_y                  7043 non-null object
Payment Method_y                     7043 non-null object
Monthly Charge                       7043 non-null float64
Total Charges_y                      7043 non-null float64
Total Refunds                        7043 non-null float64
Total Extra Data Charges             7043 non-null int64
Total Long Distance Charges          7043 non-null float64
Total Revenue                        7043 non-null float64
Count                                7043 non-null int64
Quarter_y                            7043 non-null object
Satisfaction Score                   7043 non-null int64
Customer Status                      7043 non-null object
Churn Label_y                        7043 non-null object
Churn Value_y                        7043 non-null int64
Churn Score_y                        7043 non-null int64
CLTV_y                               7043 non-null int64
Churn Category                       1869 non-null object
Churn Reason_y                       1869 non-null object
dtypes: float64(11), int64(21), object(56)
memory usage: 4.8+ MB

In [48]:
rawData.drop(rawData.filter(regex='_y$').columns.tolist(),axis=1, inplace=True)

In [52]:
rawData.columns = rawData.columns.str.replace(' ', '')
rawData.columns = rawData.columns.str.replace('_x', '')

In [53]:
rawData.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7043 entries, 0 to 7042
Data columns (total 59 columns):
CustomerID                       7043 non-null object
Count                            7043 non-null int64
Country                          7043 non-null object
State                            7043 non-null object
City                             7043 non-null object
ZipCode                          7043 non-null int64
LatLong                          7043 non-null object
Latitude                         7043 non-null float64
Longitude                        7043 non-null float64
Gender                           7043 non-null object
SeniorCitizen                    7043 non-null object
Partner                          7043 non-null object
Dependents                       7043 non-null object
TenureMonths                     7043 non-null int64
PhoneService                     7043 non-null object
MultipleLines                    7043 non-null object
InternetService                  7043 non-null object
OnlineSecurity                   7043 non-null object
OnlineBackup                     7043 non-null object
DeviceProtection                 7043 non-null object
TechSupport                      7043 non-null object
StreamingTV                      7043 non-null object
StreamingMovies                  7043 non-null object
Contract                         7043 non-null object
PaperlessBilling                 7043 non-null object
PaymentMethod                    7043 non-null object
MonthlyCharges                   7043 non-null float64
TotalCharges                     7043 non-null object
ChurnLabel                       7043 non-null object
ChurnValue                       7043 non-null int64
ChurnScore                       7043 non-null int64
CLTV                             7043 non-null int64
ChurnReason                      1869 non-null object
Age                              7043 non-null int64
Under30                          7043 non-null object
Married                          7043 non-null object
NumberofDependents               7043 non-null int64
Count                            7043 non-null int64
Quarter                          7043 non-null object
ReferredaFriend                  7043 non-null object
NumberofReferrals                7043 non-null int64
TenureinMonths                   7043 non-null int64
Offer                            7043 non-null object
AvgMonthlyLongDistanceCharges    7043 non-null float64
InternetType                     7043 non-null object
AvgMonthlyGBDownload             7043 non-null int64
DeviceProtectionPlan             7043 non-null object
PremiumTechSupport               7043 non-null object
StreamingMusic                   7043 non-null object
UnlimitedData                    7043 non-null object
MonthlyCharge                    7043 non-null float64
TotalRefunds                     7043 non-null float64
TotalExtraDataCharges            7043 non-null int64
TotalLongDistanceCharges         7043 non-null float64
TotalRevenue                     7043 non-null float64
Count                            7043 non-null int64
SatisfactionScore                7043 non-null int64
CustomerStatus                   7043 non-null object
ChurnCategory                    1869 non-null object
dtypes: float64(8), int64(15), object(36)
memory usage: 3.2+ MB

In [56]:
rawData =  rawData.drop(['Count','Country','State','LatLong','Latitude','Longitude',
                        'Partner','ChurnLabel','ChurnCategory','Quarter','CustomerStatus','ChurnCategory'], axis=1)

In [68]:
reason = rawData.groupby(['ChurnReason'])\
    .agg({'ChurnReason': 'count'})
reason.rename(columns={"ChurnReason":'count'}).sort_values(by='count',ascending=False)

                                           count
ChurnReason
Attitude of support person                   192
Competitor offered higher download speeds    189
Competitor offered more data                 162
Don't know                                   154
Competitor made better offer                 140
Attitude of service provider                 135
Competitor had better devices                130
Network reliability                          103
Product dissatisfaction                      102
Price too high                                98
Service dissatisfaction                       89
Lack of self-service on Website               88
Extra data charges                            57
Moved                                         53
Limited range of services                     44
Long distance charges                         44
Lack of affordable download/upload speed      44
Poor expertise of phone support               20
Poor expertise of online support              19
Deceased                                       6

In [73]:
reasontoCat={
"Attitude of support person":"attitude",
"Competitor offered higher download speeds":"service",
"Competitor offered more data":"service",
"Don't know":"others",
"Competitor made better offer":"price",
"Attitude of service provider":"attitude",
"Competitor had better devices":"service",
"Network reliability":"service",
"Product dissatisfaction":"service",
"Price too high":"price",
"Service dissatisfaction":"service",
"Lack of self-service on Website":"service",
"Extra data charges":"price",
"Moved":"others",
"Limited range of services":"others",
"Long distance charges":"price",
"Lack of affordable download/upload speed":"price",
"Poor expertise of phone support":"attitude",
"Poor expertise of online support":"attitude",
"Deceased":"others"
}

In [74]:
rawData['ChurnReasonCategory'] = rawData['ChurnReason'].map(reasontoCat)

In [75]:
rawData.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7043 entries, 0 to 7042
Data columns (total 47 columns):
CustomerID                       7043 non-null object
City                             7043 non-null object
ZipCode                          7043 non-null int64
Gender                           7043 non-null object
SeniorCitizen                    7043 non-null object
Dependents                       7043 non-null object
TenureMonths                     7043 non-null int64
PhoneService                     7043 non-null object
MultipleLines                    7043 non-null object
InternetService                  7043 non-null object
OnlineSecurity                   7043 non-null object
OnlineBackup                     7043 non-null object
DeviceProtection                 7043 non-null object
TechSupport                      7043 non-null object
StreamingTV                      7043 non-null object
StreamingMovies                  7043 non-null object
Contract                         7043 non-null object
PaperlessBilling                 7043 non-null object
PaymentMethod                    7043 non-null object
MonthlyCharges                   7043 non-null float64
TotalCharges                     7043 non-null object
ChurnValue                       7043 non-null int64
ChurnScore                       7043 non-null int64
CLTV                             7043 non-null int64
ChurnReason                      1869 non-null object
Age                              7043 non-null int64
Under30                          7043 non-null object
Married                          7043 non-null object
NumberofDependents               7043 non-null int64
ReferredaFriend                  7043 non-null object
NumberofReferrals                7043 non-null int64
TenureinMonths                   7043 non-null int64
Offer                            7043 non-null object
AvgMonthlyLongDistanceCharges    7043 non-null float64
InternetType                     7043 non-null object
AvgMonthlyGBDownload             7043 non-null int64
DeviceProtectionPlan             7043 non-null object
PremiumTechSupport               7043 non-null object
StreamingMusic                   7043 non-null object
UnlimitedData                    7043 non-null object
MonthlyCharge                    7043 non-null float64
TotalRefunds                     7043 non-null float64
TotalExtraDataCharges            7043 non-null int64
TotalLongDistanceCharges         7043 non-null float64
TotalRevenue                     7043 non-null float64
SatisfactionScore                7043 non-null int64
ChurnReasonCategory              1869 non-null object
dtypes: float64(6), int64(12), object(29)
memory usage: 2.6+ MB

In [76]:
reason = rawData.groupby(['ChurnReasonCategory','ChurnReason'])\
    .agg({'ChurnReason': 'count'})

In [77]:
reason

                                                               ChurnReason
ChurnReasonCategory ChurnReason
attitude            Attitude of service provider                       135
                    Attitude of support person                         192
                    Poor expertise of online support                    19
                    Poor expertise of phone support                     20
others              Deceased                                             6
                    Don't know                                         154
                    Limited range of services                           44
                    Moved                                               53
price               Competitor made better offer                       140
                    Extra data charges                                  57
                    Lack of affordable download/upload speed            44
                    Long distance charges                               44
                    Price too high                                      98
service             Competitor had better devices                      130
                    Competitor offered higher download speeds          189
                    Competitor offered more data                       162
                    Lack of self-service on Website                     88
                    Network reliability                                103
                    Product dissatisfaction                            102
                    Service dissatisfaction                             89

In [80]:
rawData.to_csv('telecomdata.csv',index=True)

## Categorical Variable
Gender	SeniorCitizen	Dependents\
PhoneService	MultipleLines	InternetService	OnlineSecurity	OnlineBackup	DeviceProtection	TechSupport	StreamingTV	StreamingMovies	Contract	PaperlessBilling	PaymentMethod\
ChurnValue ChurnReason	Under30	Married	ReferredaFriend Offer	InternetType	DeviceProtectionPlan	PremiumTechSupport	StreamingMusic	UnlimitedData	ChurnReasonCategory

## Ordered Categorical Variable
SatisfactionScore